server:
  port: 8080
  shutdown: graceful

# 日志级别 (名称以logging.level开头，后面跟要输入日志的包名， 这里定义的级别优先于logback.xml里定义的级别)
logging:
  level:
    root: info
    cn.udream.spring.eventdrive: debug

spring:
  application:
    name: eventdriver
  lifecycle:
    timeout-per-shutdown-phase: 20s
  redis:
    password:
    cluster:
      nodes: 172.16.0.230:6381, 172.16.0.230:6382, 172.16.0.231:6381, 172.16.0.231:6382, 172.16.0.232:6381, 172.16.0.232:6382
      max-redirects: 6
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
