server:
  port: 8080
  shutdown: graceful

# 日志级别 (名称以logging.level开头，后面跟要输入日志的包名， 这里定义的级别优先于logback.xml里定义的级别)
logging:
  level:
    root: info
    cn.udream.spring.eventdrive: debug

spring:
  application:
    name: eventdriver
  lifecycle:
    timeout-per-shutdown-phase: 20s
  redis:
    host: 127.0.0.1
    port: 6379
    password: Zhiyuan20160416
    timeout: 6000       # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接